version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null # Regla 1: Completitud

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null # Regla 1: Completitud

  - name: stg_sales
    columns:
      - name: sale_id
        tests:
          - not_null # Regla 1: Completitud
          -- Regla 3: Unicidad (Prueba si el ID no se repite)
          - unique 
      - name: customer_id
        tests:
          - not_null
          - relationships: # Regla 4: Integridad Referencial (Validar que el cliente exista en su maestra)
              to: ref('stg_customers')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships: # Regla 4: Integridad Referencial (Validar que el producto exista en su maestra)
              to: ref('stg_products')
              field: product_id